config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_scope :user do
    authenticated :user do
      root :to => 'pages#home', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  resources :posts, only: [:index, :new, :show, :create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :notifications, only: :index
end

app/views/layouts/_footer.html.erb
<footer>
  <% if user_signed_in? %>
   <%= link_to 'Post', new_post_url %>
  <% else %>
   <h1>InstantApp</h1>
  <% end %>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <ul class="nav">
      <% if user_signed_in? %>
        <li><%= link_to 'トップページ', authenticated_root_path %></li>
        <%= render 'layouts/search_form' %>
        <li><%= link_to 'マイページ', current_user %></li>
        <% if unchecked_notifications.any? %>
          <li><%= link_to '通知(未確認)', notifications_path %></li>
        <% else %>
          <li><%= link_to '通知', notifications_path %></li>
        <% end %>
        <li><%= link_to 'プロフィール変更', edit_user_registration_path %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'サインアップ', new_user_registration_path %></li>
        <li><%= link_to 'ログイン', new_user_session_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_search_form.html.erb
<%= search_form_for @q, url: posts_path do |f| %>
  <%= f.search_field :caption_cont, placeholder: "写真の説明で検索する" %>

  <%= f.submit "検索", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= document_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <%= render "layouts/header" %>
      <div class="container">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>
      </div>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>